---
- name: This playbook will be for HTTP Purpose
  hosts: server
  tasks:
   - name: This module will install httpd
     yum:
      name: httpd
      state: installed
   - name: This module will start http service
     service:
      name: httpd
      state: started
      enabled: yes
