---
- name: This playbook will be for HTTP Purpose
  hosts: server
  tasks:
   - name: This module will install httpd
     yum:
      name: httpd
      state: installed
     tags:
      - installation
   - name: This module will start http service
     service:
      name: httpd
      state: started
      enabled: yes
     tags:
      - service
   - name: This module will copy the index file to server
     copy:
      src: /opt/myplaybooks/index.html
      dest: /var/www/html
     tags:
      - copy
    
